"""
Chatbot service.

This module is responsible for:
1. Connecting to the Gemini API.
2. Maintaining the current conversation.
3. Sending user messages with conversation context.
4. Returning Gemini's generated response.
"""

from google import genai

from config.settings import GEMINI_API_KEY


# ---------------------------------------------------------
# Create Gemini client
# ---------------------------------------------------------

# Create a reusable Gemini client using the API key
# loaded securely from the .env file.
client = genai.Client(api_key=GEMINI_API_KEY)


# ---------------------------------------------------------
# Conversation state
# ---------------------------------------------------------

# Store the ID of the previous Gemini interaction.
#
# This allows the next interaction to continue
# from the previous conversation context.
previous_interaction_id = None


# ---------------------------------------------------------
# Generate Gemini response
# ---------------------------------------------------------

def generate_response(user_message: str) -> str:
    """
    Generate an AI response for the user's message.

    The previous interaction ID is used to maintain
    conversation context between messages.

    Args:
        user_message: The message entered by the user.

    Returns:
        The text response generated by Gemini.
    """

    global previous_interaction_id


    # -----------------------------------------------------
    # Create Gemini interaction
    # -----------------------------------------------------

    # Send the user's message to Gemini.
    #
    # If a previous interaction exists, Gemini can use
    # that interaction as the conversation context.
    if previous_interaction_id:

        interaction = client.interactions.create(
            model="gemini-3.6-flash",
            input=user_message,
            previous_interaction_id=previous_interaction_id,
        )

    else:

        # Create the first interaction when there is
        # no previous conversation.
        interaction = client.interactions.create(
            model="gemini-3.6-flash",
            input=user_message,
        )


    # -----------------------------------------------------
    # Save interaction ID
    # -----------------------------------------------------

    # Store the current interaction ID so that the
    # next user message can continue this conversation.
    previous_interaction_id = interaction.id


    # -----------------------------------------------------
    # Return Gemini response
    # -----------------------------------------------------

    # Return the generated text to the Streamlit application.
    return interaction.output_text


# ---------------------------------------------------------
# Reset conversation
# ---------------------------------------------------------

def reset_conversation() -> None:
    """
    Reset the Gemini conversation context.

    This allows the user to start a completely
    new conversation.
    """

    global previous_interaction_id

    # Remove the previous interaction ID so that
    # Gemini starts a fresh conversation.
    previous_interaction_id = None